<table width="100%">
    <thead>
    <tr>

        <td colspan="7" class="primary_line">
         Identificação do Requerente:
        </td>
    </tr>
    </thead>
    <tbody>
        <tr>
            <td><b>
                Categoria:
                </b></td>
            <td colspan="5" style="text-align: left">
                Demais Servidores
            </td>
            <td colspan="4"></td>
        </tr>
        <tr>
            <td><b>
                Nome Completo:
                </b></td>
            <td>
                Nome do Servidor
            </td>
            <td><b>
                CPF:
                </b></td>
            <td>
                000.000.000-00
            </td>
            <td><b>
                Cargo:
                </b></td>
            <td>
                Cargo Ocupado Pelo Servidor Requerente da Diária
            </td>
        </tr>
        <tr>
        <td colspan="7" class="primary_line">
        Dados Bancários:
        </td>
        </tr>
        <tr>
            <td><b>
            Banco:
            </b></td>
            <td>
                banco1
            </td>
            <td><b>
            Agência:
            </b></td>
            <td>
                0012
            </td>
            <td><b>
            Conta:
            </b></td>
            <td>
                12345-6
            </td>
        </tr>

    </tbody>
    <tbody>
    <tr >
        <td colspan="7" class="primary_line">
            Identificação do Afastamento
        </td>
    </tr>
    <tr>
        <td>
            <b>Tipo de Viagem:</b>
        </td>
        <td>
            Com Pernoite
        </td>
        <td>
            <b>Localização: </b>
        </td>
        <td colspan="3">
            Capital do Estado e Demais Localidades
        </td>
    </tr>
<tr>
    <td colspan="7" class="primary_line">
    Objetivo da Viagem:
    </td>
</tr>
    <tr rowspan="6">
        <td colspan="7"><br>
            Participar de capacitação referente a alternativas de incrementos das receitas municipais, na Assomasul, em Campo Grande/MS, nos dias 29 e 30 de maio de 2019.
        <br>
        </td>
    </tr>
    <tr>
        <td>
            <b>Meio de Transporte: </b>
        </td>
        <td colspan="6">
            Veículo Oficial
        </td>
    </tr>
    <tr>
        <td>
            <b>Local de Origem: </b>
        </td>
        <td colspan="2">
            Figueirão - MS
        </td>
        <td>
            <b>Local de Destino: </b>
        </td>
        <td colspan="2">
            Campo Grande - MS
        </td>
    </tr>
    <tr>
        <td>
            <b>Início da Permanência: </b>
        </td>
        <td colspan="2">
            03/06/2019
        </td>
        <td>
            <b>Final da Permanência</b>
        </td>
        <td colspan="2">
            06/06/2019
        </td>
    </tr>
    <tr>
        <td colspan="7" class="primary_line">
            Identificação do Valor do Quilômetro Rodado (Veículo Próprio):
        </td>
    </tr>
    <tr>
        <td>
            <b>Quantidade:</b>
        </td>
        <td>
            255
        </td>
        <td>
            <b>Valor Unitário: </b>
        </td>
        <td>
            R$ 2,50
        </td>
        <td>
            <b>Valor Total:</b>
        </td>
        <td>
            R$ 637,50
        </td>

    </tr>
    <tr>
        <td colspan="7" class="primary_line">
            Identificação do Valor da Diária:
        </td>
    </tr>
    <tr>
        <td>
            <b>Quantidade:</b>
        </td>
        <td>
            1
        </td>
        <td>
            <b>Valor Unitário: </b>
        </td>
        <td>
            R$ 200,00
        </td>
        <td>
            <b>Valor Total:</b>
        </td>
        <td>
            R$ 200,00
        </td>
    </tr>
    <tr>
        <td colspan="7">
            <br>
            <p>
                Venho por meio desta, requerer autorização para <b>viagem</b> conforme descrito neste formulário, bem como o recebimento da respectiva <b>diária</b>.
            </p><br>
        </td>
    </tr>
    </tbody>
</table>
<center>
    <br>
    <p>
        Figueirão,  03 de Junho de 2019
    </p>
    <div class="line_sign">
        <hr >
        <p>
            Assinatura do Requerente
        </p>
    </div>

    <div class="line_sign">
        <hr >
        <p>
            Assinatura e Carimbo <small>(ordenador de Despesa)</small>
        </p>
    </div>
    <button class="button" onclick="printPage();"><i class="fa fa-print"></i><b>Imprimir</b></button>
</center>