<?php
require_once(views."theme/header.phtml");
?>

    <div class="container-doc">
        <div>
        <table class="table table-sm table bordered">
            <thead>
                <tr>
                    <td>
                        <img class="brasao-doc" src="https://www.figueirao.ms.gov.br/wp-content/uploads/2017/05/brasao-figueirao1.png" alt="Brsão Figueirão" >
                    </td>
                    <td>
                        <div class="">
                            
                        </div>
                        <h4><b>
                            MUNICÍPIO DE FIGUEIRÃO
                        </b></H4>
                        <H6></b>
                            MATO GROSSO DO SUL
                        </H6>
                    </td>
                    <td>
                    <p><b>
                    ANEXO I - FORMULÁRIO DE SOLICITAÇÃO DE CONCESSÃO DE DIÁRIAS 
                    </b></p>
                    </td>
                </tr>
            </thead>
        </table>
    </div>