<?php
/**
 * Created by PhpStorm.
 * User: Marcos
 * Date: 04/06/2019
 * Time: 08:41
 */
?>
<div class="container">
    <form action="" method="post">
        <label for="cpf">CPF</label>
        <input type="text" name="cpf" id="cpf" class="form-control" required autofocus>
        <label for="tipo">Tipo de Viagem</label>
        <select id="pernoite" name="pernoite" class="form-control" required>
            <option value="false">Sem Pernoite</option>
            <option value="true">Com Pernoite</option>
        </select>
        <label for="local">Destino</label>
        <select id="local" name="local" class="form-control" required>
            <option value="1">Fora do Estado</option>
            <option value="2">Capital do Estado e Demais Municípios</option>
            <option value="3">Municípios Limítrofes</option>
        </select><br>
        <input type="text" id="origem" name="origem" class="form-control" required placeholder="Local de saída da viagem"><br>
        <input type="text" id="destino" name="destino" class="form-control" required placeholder="Local de destino da viagem">
        <label for="carro">Veículo</label>
        <select id="carro" name="carro" class="form-control" required>
            <option value="1">Veículo Oficial</option>
            <option value="2">Veículo Próprio</option>
            <option value="3">Transporte Rodoviário</option>
            <option value="4">Transporte Aéreo</option>
        </select>
        <label for="permanencia">Permanência</label>
        <div class="form-inline">
                <label for="inicio">Início</label>
                <input class="form-control mb-2 mr-sm-2" type="date" name="inicio" id="inicio" required onchange="retroativo(this.value)">
                <label for="fim">Fim</label>
                <input class="form-control mb-2 mr-sm-2" type="date" name="fim" id="fim" required onchange="validaFim(this.value)">
        </div>

    </form>
    <center>
        <p class="muted" style="color: #900" id="msg_retroativo"></p>
    </center>
</div>